version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/todo_list_application"
    schedule:
      interval: "daily"
    labels:
      - "dependabot-security-patch"  # 自動マージ用のラベルを追加
  # TODO: 許可するバージョンアップレベルを指定できるようにしておく（運用するものはメジャーは自動アップデートでなくしておく）

  - package-ecosystem: "npm"
    directory: "/todo_list_next"
    schedule:
      interval: "daily"
    labels:
      - "dependabot-security-patch"  # 自動マージ用のラベルを追加

  - package-ecosystem: "npm"
    directory: "/todo_list_view"
    ignore:
      - dependency-type: "all"
    schedule:
      interval: "monthly"
  - package-ecosystem: "bundler"
    directory: "/tasklog"
    ignore:
      - dependency-type: "all"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/tasklog"
    ignore:
      - dependency-type: "all"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/terraform"
    ignore:
      - dependency-type: "all"
    schedule:
      interval: "monthly"