version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/todo_list_application"
    schedule:
      interval: "daily" # デバッグ # "weekly"
      time: "02:20" # デバッグ
    allow:
      - dependency-type: "security"
    labels:
      - "dependabot-security-patch"  # 自動マージ用のラベルを追加

  - package-ecosystem: "npm"
    directory: "/todo_list_next"
    schedule:
      interval: "daily" # デバッグ # "weekly"
      time: "02:20" # デバッグ
    allow:
      - dependency-type: "security"
    labels:
      - "dependabot-security-patch"  # 自動マージ用のラベルを追加
