version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/todo_list_application"
    schedule:
      interval: "daily"
    labels:
      - "dependabot-security-patch"  # 自動マージ用のラベルを追加

  - package-ecosystem: "npm"
    directory: "/todo_list_next"
    schedule:
      interval: "daily"
    labels:
      - "dependabot-security-patch"  # 自動マージ用のラベルを追加
