# backendはGithubActionでイメージ更新
version: 0.2

phases:
  install:
    commands:
      - mkdir -p ~/.docker/cli-plugins
      - chmod -R 755 ~/.docker/cli-plugins
      - echo "Installing necessary tools"
      - curl -L https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REGISTRY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - REPOSITORY_URI=${REGISTRY_URI}/${ECR_REPOSITORY}
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${REGISTRY_URI}
  
  build:
    commands:
      - echo "(開発メモコメント)構築試行錯誤を最近してないからECR更新をコメントアウト。やるときになったらコメントアウトスイッチング"
      # - echo Build started on `date`
      # - IMAGE_TAG=latest
      # - REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      # - IMAGE_WITH_TAG=${ECR_REPOSITORY}:$IMAGE_TAG
      # - docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$IMAGE_WITH_TAG ./todo_list_next --push

env:
  variables:
    ECR_REPOSITORY: "todo_app_front"
    AWS_DEFAULT_REGION: "ap-northeast-1"
