version: '3'
services:
  todo_app_api:
    container_name: todo_api
    build: ./todo_list_application
    command: "/root/todo_list_application/entrypoint.sh"
    ports:
      - "30418:30418"
    volumes:
      - ./todo_list_application:/root/todo_list_application

  # todo_app_view:
  #   container_name: todo_view
  #   build: ./todo_list_view
  #   command: ". /root/todo_list_view/entrypoint.sh"
  #   ports:
  #     - "30419:30419"
  #   volumes:
  #     - ./todo_list_view:/root/todo_list_view
  
  todo_app_next:
    container_name: todo_next
    build: ./todo_list_next
    command: "/root/todo_list_next/entrypoint.sh"
    ports:
      - "30504:30504"
    volumes:
      - ./todo_list_next:/root/todo_list_next
  
  selenium-hub:
    image: selenium/hub:3.141.59-20200409
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-20200409
    # volumes:
    #   - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
