name: Trigger Dependabot
on:
  workflow_dispatch:  # 手動でワークフローを実行するためのトリガー

jobs:
  trigger_dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dependabot Updates
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/setsumaru1992/todo_list_with_modern_environment/dependabot/alerts/checks
