name: trigger auto merge dependabot security pr
on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.event.label.name == 'dependabot-security-patch'
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge Dependabot PRs
        run: gh pr merge --auto --merge ${{github.event.pull_request.html_url}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
