name: trigger auto merge dependabot security pr
on:
  pull_request:
    types:
      - labeled

jobs:
  auto-merge:
    if: github.event.label.name == 'dependabot-security-patch'
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge Dependabot PRs
        uses: "peter-evans/enable-pull-request-automerge@v2"
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
